repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^src/util/ascii/
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^src/util/ascii/

  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
        exclude: ^src/util/ascii/

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        exclude: |
            (?x)^(
                ^docs/|
                ^src/util/ascii/
            )$

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.2.2"
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
        exclude: ^src/util/ascii/
